ALTER TABLE users ADD COLUMN name VARCHAR(255);
ALTER TABLE users ADD COLUMN phone VARCHAR(255);

UPDATE users SET name = 'Usuario Generico' WHERE name IS NULL;
UPDATE users SET phone = '000-0000' WHERE phone IS NULL;

ALTER TABLE users ALTER COLUMN name SET NOT NULL;
ALTER TABLE users ALTER COLUMN phone SET NOT NULL;
