spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mercadito_dev
    username: merca
    password: merca
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration

security:
  jwt:
    issuer: mercadito-uam
    expiration-minutes: 120
    secret: ${JWT_SECRET:esto-es-una-clave-larga-de-32-caracteres-minimo-1234}
logging:
  level:
    org.springframework.security: DEBUG