name: CI Backend Maven

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: mercadito_test
          POSTGRES_USER: merca
          POSTGRES_PASSWORD: merca
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U merca -d mercadito_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mercadito_test
      SPRING_DATASOURCE_USERNAME: merca
      SPRING_DATASOURCE_PASSWORD: merca
      SPRING_PROFILES_ACTIVE: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Esperar a que arranque Postgres
        run: |
          for i in {1..10}; do
            if nc -z postgres 5432; then
              echo "Postgres listo ✅"
              exit 0
            fi
            echo "Esperando Postgres..."
            sleep 3
          done
          echo "Postgres no arrancó a tiempo "
          exit 1

      - name: Build & Test (mvnw clean verify)
        working-directory: ./backend
        run: ./mvnw clean verify -B
