name: CI Backend Maven

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: mercadito
          POSTGRES_USER: merca
          POSTGRES_PASSWORD: merca
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U merca -d mercadito"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Install netcat for waiting
        run: sudo apt-get update && sudo apt-get install -y netcat-openbsd

      - name: Wait for Postgres to be ready
        run: |
          echo "Esperando a que Postgres esté disponible..."
          for i in {1..30}; do
            if nc -z localhost 5432; then
              echo "✅ Postgres listo!"
              break
            fi
            echo "⏳ Esperando..."
            sleep 5
          done

      - name: Make mvnw executable
        working-directory: backend
        run: chmod +x mvnw

      - name: Build & test with Maven
        working-directory: ./backend
        env:
          SPRING_PROFILES_ACTIVE: test
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/mercadito
          SPRING_DATASOURCE_USERNAME: merca
          SPRING_DATASOURCE_PASSWORD: merca
          SPRING_JPA_HIBERNATE_DDL_AUTO: validate
          SPRING_FLYWAY_ENABLED: "true"
        run: ./mvnw -B clean verify
